title: <p align="center"> Himaprasoon </p>


remote_theme: pages-themes/minimal@v0.2.0



logo: /assets/img/hima.png

description:
  <p align="center">
#  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/himaprasoon/">LinkedIn</a> |
  <a href="https://github.com/himaprasoonpt">GitHub</a>
  
  <br>   
  AI  Engineer @ Razorthink
  <br>
  </p>

plugins:
- jekyll-remote-theme

theme: jekyll-theme-minimal